spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  messages:
    basename: messages
    fallback-to-system-locale: false
bucket: C:\Users\anarm\learning\own-projects\online-shop\images
